<?php
/**
 * @package   QWcrm
 * @author    Jon Brown https://quantumwarp.com/
 * @copyright Copyright (C) 2016 - 2017 Jon Brown, All rights reserved.
 * @license   GNU/GPLv3 or later; https://www.gnu.org/licenses/gpl.html
 */

defined('_QWEXEC') or die;

//require(CINCLUDES_DIR.'client.php');
//require(CINCLUDES_DIR.'user.php');

// Prevent undefined variable errors
\CMSApplication::$VAR['login_username'] = isset(\CMSApplication::$VAR['login_username']) ? \CMSApplication::$VAR['login_username'] : null;
\CMSApplication::$VAR['login_pwd'] = isset(\CMSApplication::$VAR['login_pwd']) ? \CMSApplication::$VAR['login_pwd'] : null;
\CMSApplication::$VAR['action'] = isset(\CMSApplication::$VAR['action']) ? \CMSApplication::$VAR['action'] : null;

// Get variables in correct format for login()
$credentials['username'] = \CMSApplication::$VAR['login_username'];
$credentials['password'] = \CMSApplication::$VAR['login_pwd'];
if ($config->get('remember_me') && isset(\CMSApplication::$VAR['remember'])) {
    $options['remember'] = \CMSApplication::$VAR['remember'];
} else {
    $options = array();
}

// If login submitted 
if(\CMSApplication::$VAR['action'] === 'login') {
    
    // recaptcha is disabled || recaptcha is enabled and passes authentication
    if(!$config->get('recaptcha') || ($config->get('recaptcha') && authenticate_recaptcha($config->get('recaptcha_secret_key'), \CMSApplication::$VAR['g-recaptcha-response']))) {

        /* Allowed to submit */        

        // Log the user in
        if(login(\CMSApplication::$VAR, $credentials, $options)) {

            force_page('index.php');

        } else {
            // do nothing reload login page
        }
            
        

    } else {

        /* Failed reCAPTCHA  */         

        // Allow login page to load with reCAPTCHA warning message (already generated by authenticate_recaptcha())

    }
    
}

// Remove credentials and options as no longer needed
unset($credentials);
unset($options);

// If logout is set, then log the user off
if (\CMSApplication::$VAR['action'] == 'logout') {    
    logout();
}

// Build the page
$smarty->assign('remember_me', $config->get('remember_me'));
$smarty->assign('recaptcha', $config->get('recaptcha'));
$smarty->assign('recaptcha_site_key', $config->get('recaptcha_site_key'));

